defmodule Aewallet.Mnemonic do
  @moduledoc """
  Module for generating a mnemonic phrase following the BIP-39 standard
  """

  @doc """
  Generates a phrase from a given list of rows
  generated by the GenerateIndexes module, where each index
  represents a row from the wordlist.txt file
  ## Examples
      iex> Mnemonic.generate_phrase([1223, 32, 453])
      "ocean advice december"
  """
  @spec generate_phrase(list()) :: String.t()
  def generate_phrase(rows) do
    phrase = for row <- rows do
      elem(get_wordlist(), row) <> " "
    end
    |> List.to_string()
    |> String.trim()
  end

  @doc """
  Finds the directory of the priv folder in the :aewallet project
  and reads the wordlist.txt file inside it.
  Returns a tuple with all the words
  """
  @spec get_wordlist :: tuple()
  def get_wordlist do
    {:ok, word_list} =
      :aewallet
      |> :code.priv_dir()
      |> Path.join("wordlist.txt")
      |> File.read()

    word_list
    |> String.split("\n")
    |> List.to_tuple()
  end

end
